config/routes.rb
HappinessProject::Application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'settings', to: 'users#edit', as: 'settings'
  get "static/index"
  resources :users
  resources :sessions
  resources :entries
  
  root to: 'entries#new'
  
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :neg_karma, :pos_karma, :rating, :user_id, :note
  belongs_to :user

  validates_presence_of :rating
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation
  validates_uniqueness_of :email

  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      redirect_to login_url if current_user.nil?
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authorize
  
  def index
    @user = current_user
    @entries = @user.entries.order(:created_at).reverse_order
  end

  def new
    @entry = Entry.new    
  end

  def create
    @entry = Entry.new(params[:entry])
    @entry.user = current_user
  
    respond_to do |format|
      if @entry.save
        format.html { redirect_to entries_path, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password invalid"
      render "new"    
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  # def index
  #   @users = User.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @users }
  #   end
  # end

  # # GET /users/1
  # # GET /users/1.json
  # def show
  #   @user = User.find(params[:id])
  #   @entries = @user.entries

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @user }
  #   end
  # end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        UserMailer.signup_confirmation(@user).deliver
        format.html { redirect_to new_entry_path, notice: 'Thank you for signing up!' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to entries_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # def destroy
  #   @user = User.find(params[:id])
  #   @user.destroy

  #   respond_to do |format|
  #     format.html { redirect_to users_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then 'info'
      when :error then 'error'
      when :alert then 'warning'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
<% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <%= f.label 'Mood Rating' %>
  <%= radio_button("entry", "rating", 1) %> 1
  <%= radio_button("entry", "rating", 2) %> 2
  <%= radio_button("entry", "rating", 3) %> 3
  <%= radio_button("entry", "rating", 4) %> 4
  <%= radio_button("entry", "rating", 5) %> 5
  <br>
  <br>

  <%= f.label 'Notes' %>
  <%= f.text_field :note %>




  <%= f.label 'Positive Karma' %>
 
  <%= f.text_field :pos_karma %>

  <%= f.label 'Negative Karma' %>
  <%= f.text_field :neg_karma %>


  <%= f.submit 'save', :class => 'btn' %>
<% end %>

app/views/entries/index.html.erb
<%= link_to 'New Entry', new_entry_path, :class => "btn" %>

  <table class="table">
    <tr>
      <th>Rating</th>
      <th>Note</th>
      <th>Positive</th>
      <th>Negative</th>
      <th>Timestamp</th>
      <th></th>
    </tr>
  <% @entries.each do |e| %>
    <tr>
      <td><%= e.rating %></td>
      <td><%= e.note %></td>
      <td><%= e.pos_karma %></td>
      <td><%= e.neg_karma %></td>
      <td><%= e.created_at.in_time_zone('Eastern Time (US & Canada)').to_s(:long) %></td>
      <td><%= link_to 'delete', e, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  

app/views/entries/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Floating Journey" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>


    <div class="container">
      <div class="span10">
        <div class="pull-right">
        <ul class="nav nav-pills">
        <% if current_user %>          
          <li><%= link_to 'Entries', entries_path %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.email %>
                <b class="caret"></b>
              </a>
            <ul class="dropdown-menu">
              <!-- links -->
              <li><%= link_to 'My Settings', settings_path %></li>
              <li><%= link_to "logout", logout_path %></li>      
            </ul>
          </li>
        
        <% else %>
            <li><%= link_to "sign up", signup_path %></li>
            <li><%= link_to "login", login_path %></li>
        <% end %>
        </ul>
      </div>

        <h1 id="site-title"><%= link_to 'Floating Journey', '/' %></h1>
        <br />
        



        <% [:notice, :error, :alert].each do |level| %>
          <% unless flash[level].blank? %>
            <div data-alert="alert" class="alert alert-<%= flash_class(level) %> fade in">
              <a class="close" data-dismiss="alert" href="#">&times;</a>
              <%= content_tag :p, flash[level] %>
            </div>
          <% end %>
        <% end %>


        <div class="content">       
          <%= yield %>
        </div>      
      </div>
    </div>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>
<%#= link_to 'Show', @user %>
<%#= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table">
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path, :class => 'btn' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up", :class => 'btn' %></div>
<% end %>

app/views/users/show.html.erb
  <p id="notice"><%= notice %></p>

  <h3><%= @user.email %></h3>
  <%= link_to 'New Entry', new_entry_path, :class => "btn pull-right" %>

  <table class="table">
    <tr>
      <th>Positive</th>
      <th>Negative</th>
      <th>Rating</th>
      <th>Timestamp</th>
    </tr>
  <% @entries.each do |e| %>
    <tr>
      <td><%= e.pos_karma %></td>
      <td><%= e.neg_karma %></td>
      <td><%= e.rating %></td>
      <td><%= e.created_at %></td>
    </tr>
  <% end %>
  </table>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>